name: Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Interval/**'
      - 'Interval.Tests/**'
      - '.github/**'
  pull_request:
    paths:
      - 'Interval/**'
      - 'Interval.Tests/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        # Mostly to avoid GitHub rate limiting
        extra_nix_config: |
          access-tokens = github.com=${{ github.token }}

    - name: Install Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build
      run: nix develop .#ci --impure -c just build
    - name: Run testing suite
      run: nix develop .#ci --impure -c just test
