name: Nuget

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  push:
    name: Push to Nuget
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        token: ${{ github.token }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Test before releasing
        run: make test
      - name: Pack release
        run: dotnet pack -c Release /p:Version=$(echo ${{ github.ref_name }} | sed 's/v//g')
      - name: Publish the package to nuget.org
        run: dotnet nuget push */bin/Release/*.nupkg -k "${NUGET_API_KEY}" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
