name: Nuget

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  push:
    name: Push to Nuget
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Test before releasing
        run: nix develop .#ci --impure -c just test
      - name: Pack release
        run: nix develop .#ci --impure -c just pack
      - name: Publish the package to nuget.org
        run: nix develop .#ci --impure -c just release
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
