name: "[Nix] Update flake.lock"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 3 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "[Nix] Update flake.lock"
          pr-labels: |
            dependencies
            automation
